# Generated by Django 3.1 on 2021-01-29 22:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='topic',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='blog.topic'),
            preserve_default=False,
        ),
    ]
