# Generated by Django 3.0.7 on 2020-12-29 10:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0004_postlike'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postlike',
            name='likes',
        ),
        migrations.AddField(
            model_name='postlike',
            name='likes',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
