# Generated by Django 3.0.7 on 2020-12-29 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20201229_1826'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postlike',
            old_name='post_name',
            new_name='post_title',
        ),
        migrations.RenameField(
            model_name='postlike',
            old_name='likes',
            new_name='user',
        ),
    ]
