# Generated by Django 3.0.7 on 2020-12-29 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20201229_1956'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postlike',
            old_name='post_title',
            new_name='post',
        ),
    ]
