# Generated by Django 3.1 on 2021-01-30 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20210130_0818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_image',
            field=models.ImageField(blank=True, default=True, upload_to='post_images'),
            preserve_default=False,
        ),
    ]
