# Generated by Django 3.0.7 on 2020-12-30 04:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20201230_1245'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postlike',
            name='post',
        ),
        migrations.AddField(
            model_name='postlike',
            name='post',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.PROTECT, to='blog.Post'),
            preserve_default=False,
        ),
    ]
