# Generated by Django 3.1 on 2021-01-30 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20210130_0913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_image',
            field=models.ImageField(default='default_post_img.jpg', upload_to='post_images'),
        ),
    ]
